### ISSUE TITLE
Could not find native static library `WebView2LoaderStatic`

### ISSUE THREAD

**Issue by skarab42** [tauri-apps/window-shadows#3]
Hi, after adding `tauri-plugin-shadows` as dependencies, my app rebuild and i get this error

![image](https://user-images.githubusercontent.com/62928763/150156766-12d4d4da-2dc6-4625-85fb-0b84885cbec9.png)

```
Operating System - Windows, version 10.0.19042 X64

Node.js environment
  Node.js - 14.17.0
  @tauri-apps/cli - 1.0.0-beta.10

Global packages
  npm - 6.14.13
  yarn - 1.22.17

Rust environment
  rustc - 1.58.0
  cargo - 1.58.0
```

Thank you for your help

**Comment by lucasfernog** [comment]
Can you try following this: https://tauri.studio/docs/faq/

**Comment by skarab42** [comment]
I already have NugGet installed for some Unity projet.

![image](https://user-images.githubusercontent.com/62928763/150171896-591fb86d-bef1-4447-9658-34ffb9c23957.png)

**Comment by lucasfernog** [comment]
Hmm that complicates things a little bit. Can you try cloning this repo https://github.com/lucasfernog/webview2-rs and seeing the build output? Instructions can be found on Discord: https://discord.com/channels/616186924390023171/625037620996734986/931977731346923621

**Comment by skarab42** [comment]
the discord link doesn't work

**Comment by lucasfernog** [comment]
Anyway, try cloning that repo, running `cargo build` and looking for the `output` file in a folder structure that looks like this (with a similar folder name, different hash suffix):
![image](https://user-images.githubusercontent.com/20051258/150176236-e556c53f-8d34-4d5f-85b4-c134f2cd94d6.png)

**Comment by skarab42** [comment]
It looks good 
![image](https://user-images.githubusercontent.com/62928763/150179399-eddcceaa-5d6d-4162-8347-791caf0ce33d.png)

**Comment by lucasfernog** [comment]
What's the contents of the `output` file?

**Comment by skarab42** [comment]
[output.txt](https://github.com/tauri-apps/tauri-plugin-shadows/files/7899155/output.txt)

**Comment by lucasfernog** [comment]
Looks good. Did the build succeed? If not, does `C:\Users\skarab\Coding\webview2-rs\crates\bindings\.windows\x64` exist?

**Comment by skarab42** [comment]
Yes the build succeed
![image](https://user-images.githubusercontent.com/62928763/150180596-ce820198-5859-44a8-9ffa-f6b33a510a30.png)

**Comment by lucasfernog** [comment]
So it should work on your tauri app too. Can you remove the `src-tauri/target/` folder and build again? Maybe run `cargo update` on the `src-tauri` folder helps too.

**Comment by skarab42** [comment]
ok the WebView2LoaderStatic  error has gone but here is a new one
![image](https://user-images.githubusercontent.com/62928763/150181892-39988693-ee5f-45f8-9e30-8357eb3fa26b.png)

**Comment by lucasfernog** [comment]
Give me a sec, gonna fix that one. CI should have caught it :(

**Comment by lucasfernog** [comment]
Fixed it. Run `cargo update` on the `src-tauri` folder and try again :)

**Comment by skarab42** [comment]
Nice! Almost done ;)

![image](https://user-images.githubusercontent.com/62928763/150186869-5537c429-8d01-42e7-8199-61c07d415fd1.png)

Thank you very much for your help

**Comment by skarab42** [comment]
Cargo notice this error
![image](https://user-images.githubusercontent.com/62928763/150195119-7c10735a-d516-4fef-af13-6d6c09e702e5.png)
