### ISSUE TITLE
Use .ok() instead of .expect(...) for better cross platform compatability

### ISSUE THREAD

**Issue by elibroftw** [tauri-apps/window-shadows#38]
By following the usage instructions, an app will fail to run on an unsupported platform. For example, I'm testing out my template on Manjaro and the AppImage fails to run because of the set shadows fails. Who care if set shadows is not supported on a particular OS, it's a decoration not a functional necessity!

I suggest removing the .expect in place of ok

**Comment by amrbashir** [comment]
you can just choose to not call `.expect()` and ignore the error 
```rs
let _ = set_shadow(&window, true);
```
or better use it behind a compilation flag.
```rs
#[cfg(any(target_os = "macos", windows))]
set_shadow(&window, true).unwrap();
```
I will update the docs
