### ISSUE TITLE
Unused import

### ISSUE THREAD

**Issue by skarab42** [tauri-apps/window-shadows#4]
Following the previous issue i get this one:

![image](https://user-images.githubusercontent.com/62928763/150186869-5537c429-8d01-42e7-8199-61c07d415fd1.png)

Also Cargo notice this error:

![image](https://user-images.githubusercontent.com/62928763/150195119-7c10735a-d516-4fef-af13-6d6c09e702e5.png)

My `main.rs` file look like this:

```rs
#![cfg_attr(
  all(not(debug_assertions), target_os = "windows"),
  windows_subsystem = "windows"
)]

use tauri::Manager;
use tauri_plugin_shadows::Shadows;

fn main() {
  tauri::Builder::default()
    .setup(|app| {
      let window = app.get_window("main").unwrap();
      //use tauri_plugin_shadows::Shadows;
      window.set_shadow(true);
      Ok(())
    })
    .run(tauri::generate_context!())
    .expect("error while running tauri application");
```

Thank you very much for your help

_Originally posted by @skarab42 in https://github.com/tauri-apps/tauri-plugin-shadows/issues/3#issuecomment-1016719969_

**Comment by FabianLars** [comment]
I think this error means that you're not using tauris `next` branch.

**Comment by lucasfernog** [comment]
You need to use the next branch, change your Cargo.toml to this: `tauri = { git = "https://github.com/tauri-apps/tauri", branch = "next", features = [] }` filling in your features.

**Comment by skarab42** [comment]
You have seen right, thank you very much, everything works like a charm.
