### ISSUE TITLE
Add installation guide for JS users to README.md

### ISSUE THREAD

**Issue by wennerryle** [tauri-apps/window-shadows#45]
For me, as a JS user, installing this plugin is confusing since I have never worked with Rust. Thank you very much for your work!

**Comment by amrbashir** [comment]
Soon this crate will be archived, and the functionality will be integrated into tauri and since the instructions are simple, it is enough to write it here.

1. Add this line in `src-tauri/Cargo.toml` under `dependencies`
	```toml
	window-shadows = "0.2"
	```
2. in your `src-tauri/src/main.rs` add this inside the `setup` hook: 
	```rs
	   let window = app.get_window("main").unwrap();
       let _ = set_shadow(&window, true);
	```
	see this link for an exmaple: https://github.com/tauri-apps/window-shadows/blob/3fa601ce2ca1b719add4f769f9397f25d94c4693/examples/tauri/src-tauri/src/main.rs#L16-L18
